name: Djamgo Pipeline

on:
  push:
    branches:
      - master
  
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8
    - name: Coverage report
      run: |
        pip install coverage
        coverage run manage.py test
        coverage report
    - name: Django Pipeline
      run: |
        python3 manage.py test


    - name: Deploy to Digital Ocean   
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
        key: ${{secrets.SSH_KEY}} # Private or public key of the server
        username: ${{ secrets.SSH_USERNAME }}  # User of the server you want to ssh into
        if: github.ref == 'refs/heads/master' && job.status == 'success'
        run: |
        git clone git@github.com:josedlg/django-docker-cicd.git
        echo 'Deployment successful to digital ocean'

